import type { UnitDialogue } from '../../types';

export const FALLBACK_DIALOGUES: UnitDialogue[] = [
  {
    unitNumber: 1,
    title: 'İlk Temas & Dil Becerisi Sorma',
    contextTr: 'Bir trende veya ev ortamında Alman bir kadının yanında oturan Amerikalı bir adam sohbet başlatmak ister.',
    contextEn: 'An American man sitting next to a German woman on a train or at home starts a conversation.',
    contextDe: 'Ein amerikanischer Mann sitzt im Zug oder zu Hause neben einer deutschen Frau und beginnt ein Gespräch.',
    startMs: 6628,
    endMs: 17562,
    durationMs: 10934,
    audioFileName: 'Pimsleur German 1 - Unit 01.mp3',
    lines: [
      {
        id: 'de-l1-u01-s003',
        segmentIndex: 3,
        startMs: 6628,
        endMs: 8806,
        durationMs: 2178,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Entschuldigen Sie, verstehen Sie Englisch?',
        turkishText: 'Affedersiniz, İngilizce anlıyor musunuz?',
        englishExplanation: 'Formal polite address ("Sie"). "Entschuldigen Sie" = Excuse me. Verb-first position creates a yes/no question.',
      },
      {
        id: 'de-l1-u01-s004',
        segmentIndex: 4,
        startMs: 9146,
        endMs: 11406,
        durationMs: 2260,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, ich verstehe kein Englisch.',
        turkishText: 'Hayır, İngilizce anlamıyorum.',
        englishExplanation: 'Negation using "kein" for nouns without definite articles ("kein Englisch" = no English).',
      },
      {
        id: 'de-l1-u01-s005',
        segmentIndex: 5,
        startMs: 11626,
        endMs: 13978,
        durationMs: 2352,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ich verstehe ein bisschen Deutsch.',
        turkishText: 'Biraz Almanca anlıyorum.',
        englishExplanation: '"Ein bisschen" = a little bit. Standard S-V-O word order in declarative German sentences.',
      },
      {
        id: 'de-l1-u01-s006',
        segmentIndex: 6,
        startMs: 14194,
        endMs: 15730,
        durationMs: 1536,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Sind Sie Amerikaner?',
        turkishText: 'Amerikalı mısınız?',
        englishExplanation: 'Direct nationality inquiry using verb inversion ("Sind Sie...?").',
      },
      {
        id: 'de-l1-u01-s007',
        segmentIndex: 7,
        startMs: 16186,
        endMs: 17562,
        durationMs: 1376,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, Amerikaner.',
        turkishText: 'Evet, Amerikalı.',
        englishExplanation: 'Short affirmative response confirming nationality ("Amerikaner" = male American).',
      },
    ],
    keyVocab: [
      { term: 'Entschuldigen Sie', tr: 'Affedersiniz', en: 'Excuse me' },
      { term: 'Verstehen Sie...?', tr: 'Anlıyor musunuz?', en: 'Do you understand...?' },
      { term: 'Ich verstehe...', tr: 'Anlıyorum', en: 'I understand...' },
      { term: 'Kein Englisch', tr: 'Hiç İngilizce / İngilizce değil', en: 'No English' },
      { term: 'Ein bisschen', tr: 'Biraz', en: 'A little bit' },
      { term: 'Amerikaner', tr: 'Amerikalı [erkek]', en: 'American [male]' },
    ],
  },
  {
    unitNumber: 2,
    title: 'Karşılıklı Dil Durumu',
    contextTr: 'Kadın bu kez söze girerek erkeğe Almanca bilip bilmediğini sorar; karşılıklı soru sorma pekiştirilir.',
    contextEn: 'The woman asks the man if he understands German, practicing reciprocal questions.',
    contextDe: 'Die Frau fragt den Mann, ob er Deutsch versteht, um Höflichkeitsformen zu üben.',
    startMs: 6592,
    endMs: 18458,
    durationMs: 11866,
    audioFileName: 'Pimsleur German 1 - Unit 02.mp3',
    lines: [
      {
        id: 'de-l1-u02-s003',
        segmentIndex: 3,
        startMs: 6592,
        endMs: 8990,
        durationMs: 2398,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Entschuldigen Sie, verstehen Sie Deutsch?',
        turkishText: 'Affedersiniz, Almanca anlıyor musunuz?',
        englishExplanation: 'Inverted formal question to open the conversation politely.',
      },
      {
        id: 'de-l1-u02-s004',
        segmentIndex: 4,
        startMs: 9474,
        endMs: 11130,
        durationMs: 1656,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, ein bisschen.',
        turkishText: 'Evet, biraz.',
        englishExplanation: 'Affirmative response with degree modifier ("ein bisschen").',
      },
      {
        id: 'de-l1-u02-s005',
        segmentIndex: 5,
        startMs: 11626,
        endMs: 13026,
        durationMs: 1400,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Sind Sie Amerikaner?',
        turkishText: 'Amerikalı mısınız?',
        englishExplanation: 'Direct nationality question using the formal pronoun "Sie".',
      },
      {
        id: 'de-l1-u02-s006',
        segmentIndex: 6,
        startMs: 13322,
        endMs: 16258,
        durationMs: 2936,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, Amerikaner, verstehen Sie Englisch?',
        turkishText: 'Evet, Amerikalı, İngilizce anlıyor musunuz?',
        englishExplanation: 'Confirming and passing the question back to the listener.',
      },
      {
        id: 'de-l1-u02-s007',
        segmentIndex: 7,
        startMs: 16410,
        endMs: 18458,
        durationMs: 2048,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, ich verstehe kein Englisch.',
        turkishText: 'Hayır, İngilizce anlamıyorum.',
        englishExplanation: 'Reiterating the negation of capability in English.',
      },
    ],
    keyVocab: [
      { term: 'Deutsch', tr: 'Almanca', en: 'German language' },
      { term: 'Englisch', tr: 'İngilizce', en: 'English language' },
      { term: 'Ja / Nein', tr: 'Evet / Hayır', en: 'Yes / No' },
      { term: 'Ich verstehe kein...', tr: '... anlamıyorum', en: 'I do not understand [any]...' },
    ],
  },
  {
    unitNumber: 3,
    title: 'Resmi Selamlaşma & İltifat',
    contextTr: 'Bayan Meier ile Bay Gordon sokakta karşılaşır. Resmi selamlaşma, hatır sorma ve dil becerisine iltifat içerir.',
    contextEn: 'Mrs. Meier and Mr. Gordon meet on the street, greeting each other politely with compliments.',
    contextDe: 'Frau Meier und Herr Gordon treffen sich auf der Straße und begrüßen sich höflich.',
    startMs: 6682,
    endMs: 20902,
    durationMs: 14220,
    audioFileName: 'Pimsleur German 1 - Unit 03.mp3',
    lines: [
      {
        id: 'de-l1-u03-s003',
        segmentIndex: 3,
        startMs: 6682,
        endMs: 7542,
        durationMs: 860,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Guten Tag, Herr Gordon.',
        turkishText: 'İyi günler, Bay Gordon.',
        englishExplanation: 'Formal daytime greeting + Title ("Herr" = Mr.).',
      },
      {
        id: 'de-l1-u03-s004',
        segmentIndex: 4,
        startMs: 7722,
        endMs: 8966,
        durationMs: 1244,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Wie geht es Ihnen?',
        turkishText: 'Nasılsınız?',
        englishExplanation: 'Formal "How are you?" using dative pronoun "Ihnen".',
      },
      {
        id: 'de-l1-u03-s005',
        segmentIndex: 5,
        startMs: 9210,
        endMs: 10110,
        durationMs: 900,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Sehr gut, Frau Meier.',
        turkishText: 'Çok iyi, Bayan Meier.',
        englishExplanation: '"Sehr" = very. Title "Frau" = Ms./Mrs.',
      },
      {
        id: 'de-l1-u03-s006',
        segmentIndex: 6,
        startMs: 10110,
        endMs: 12518,
        durationMs: 2408,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Danke. Ah, Sie verstehen Deutsch?',
        turkishText: 'Teşekkürler. Ah, Almanca anlıyor musunuz?',
        englishExplanation: 'Rising intonation transforms statement into conversational question.',
      },
      {
        id: 'de-l1-u03-s007',
        segmentIndex: 7,
        startMs: 12826,
        endMs: 13978,
        durationMs: 1152,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Nur ein bisschen.',
        turkishText: 'Sadece biraz.',
        englishExplanation: '"Nur" = only / just (shows modesty).',
      },
      {
        id: 'de-l1-u03-s008',
        segmentIndex: 8,
        startMs: 13978,
        endMs: 15334,
        durationMs: 1356,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Sind Sie Amerikaner?',
        turkishText: 'Amerikalı mısınız?',
        englishExplanation: 'Formal nationality inquiry.',
      },
      {
        id: 'de-l1-u03-s009',
        segmentIndex: 9,
        startMs: 15674,
        endMs: 16934,
        durationMs: 1260,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, Amerikaner.',
        turkishText: 'Evet, Amerikalı.',
        englishExplanation: 'Short confirmation of nationality.',
      },
      {
        id: 'de-l1-u03-s010',
        segmentIndex: 10,
        startMs: 17178,
        endMs: 19014,
        durationMs: 1836,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Aber Sie verstehen sehr gut Deutsch.',
        turkishText: 'Ama çok iyi Almanca anlıyorsunuz.',
        englishExplanation: '"Aber" = but. Compliment on language proficiency ("sehr gut Deutsch").',
      },
      {
        id: 'de-l1-u03-s011',
        segmentIndex: 11,
        startMs: 19226,
        endMs: 20902,
        durationMs: 1676,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Nein, nein, nicht sehr gut.',
        turkishText: 'Hayır, hayır, çok iyi değil.',
        englishExplanation: '"Nicht sehr gut" = not very well (modest rejection of excessive compliment).',
      },
    ],
    keyVocab: [
      { term: 'Guten Tag', tr: 'İyi günler', en: 'Good day / Hello' },
      { term: 'Wie geht es Ihnen?', tr: 'Nasılsınız?', en: 'How are you? (formal)' },
      { term: 'Sehr gut, danke', tr: 'Çok iyi, teşekkürler', en: 'Very good, thank you' },
      { term: 'Nur ein bisschen', tr: 'Sadece biraz', en: 'Only a little' },
      { term: 'Aber', tr: 'Ama / Fakat', en: 'But' },
      { term: 'Nicht sehr gut', tr: 'Çok iyi değil', en: 'Not very well' },
    ],
  },
  {
    unitNumber: 4,
    title: 'Milliyet & Kibarca İtiraz ("Doch")',
    contextTr: 'Kadın ve erkek formlarındaki milliyet ekleri (Amerikaner vs. Amerikanerin) ve olumsuz bir cümleye kibarca itiraz için "Doch" parçacığı.',
    contextEn: 'Practicing gendered nationalities (Amerikaner/Amerikanerin) and polite contradiction with "Doch".',
    contextDe: 'Geschlechtsspezifische Nationalitäten und höflicher Widerspruch mit "Doch".',
    startMs: 6104,
    endMs: 20582,
    durationMs: 14478,
    audioFileName: 'Pimsleur German 1 - Unit 04.mp3',
    lines: [
      {
        id: 'de-l1-u04-s003',
        segmentIndex: 3,
        startMs: 6104,
        endMs: 8006,
        durationMs: 1902,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Entschuldigen Sie, sind Sie Deutscher?',
        turkishText: 'Affedersiniz, Alman mısınız?',
        englishExplanation: 'Notice "Deutscher" (masculine form for a German male).',
      },
      {
        id: 'de-l1-u04-s004',
        segmentIndex: 4,
        startMs: 8418,
        endMs: 10306,
        durationMs: 1888,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, ich bin Deutscher und Sie?',
        turkishText: 'Evet, ben Almanım, ya siz?',
        englishExplanation: '"Und Sie?" = And you? Passing the question.',
      },
      {
        id: 'de-l1-u04-s005',
        segmentIndex: 5,
        startMs: 10306,
        endMs: 11782,
        durationMs: 1476,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ich bin Amerikanerin.',
        turkishText: 'Ben Amerikalıyım.',
        englishExplanation: 'Feminine nationality suffix "-in": "Amerikanerin".',
      },
      {
        id: 'de-l1-u04-s006',
        segmentIndex: 6,
        startMs: 12248,
        endMs: 13670,
        durationMs: 1422,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Aber sie verstehen Deutsch.',
        turkishText: 'Ama Almanca anlıyorsunuz.',
        englishExplanation: 'Affirming the listener\'s comprehension ability.',
      },
      {
        id: 'de-l1-u04-s007',
        segmentIndex: 7,
        startMs: 13882,
        endMs: 16646,
        durationMs: 2764,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ach, ich verstehe ein bisschen, aber nicht sehr gut.',
        turkishText: 'Ah, biraz anlıyorum ama çok iyi değil.',
        englishExplanation: 'Conversational filler "Ach" + modest assessment.',
      },
      {
        id: 'de-l1-u04-s008',
        segmentIndex: 8,
        startMs: 17144,
        endMs: 18744,
        durationMs: 1600,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Doch, Sie verstehen sehr gut.',
        turkishText: 'Bilakis, çok iyi anlıyorsunuz.',
        englishExplanation: '"Doch!" is used to contradict a negative statement ("Oh yes you do!").',
      },
      {
        id: 'de-l1-u04-s009',
        segmentIndex: 9,
        startMs: 18744,
        endMs: 20582,
        durationMs: 1838,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, nein, nur ein bisschen.',
        turkishText: 'Hayır, hayır, sadece biraz.',
        englishExplanation: 'Playful persistence in modesty ("nur ein bisschen").',
      },
    ],
    keyVocab: [
      { term: 'Deutscher', tr: 'Alman erkek', en: 'German male' },
      { term: 'Amerikanerin', tr: 'Amerikalı kadın', en: 'American female' },
      { term: 'Und Sie?', tr: 'Ya siz?', en: 'And you?' },
      { term: 'Doch!', tr: 'Bilakis! / Aksine!', en: 'Yes, indeed! (contradicting a negative)' },
      { term: 'Ich bin...', tr: 'Ben ...\'yim', en: 'I am...' },
    ],
  },
  {
    unitNumber: 5,
    title: 'Adres/Yön Sorma & "Mir?" Kalıbı',
    contextTr: 'Sokakta bir yer/cadde sorma (Goethestraße, Opernplatz) ve beklenmedik hatır sorma sorusuna verilen şaşırma cevabı ("Mir?").',
    contextEn: 'Asking for street directions and answering "Mir? Sehr gut, danke".',
    contextDe: 'Nach dem Weg fragen und auf Befinden antworten.',
    startMs: 6564,
    endMs: 21990,
    durationMs: 15426,
    audioFileName: 'Pimsleur German 1 - Unit 05.mp3',
    lines: [
      {
        id: 'de-l1-u05-s003',
        segmentIndex: 3,
        startMs: 6564,
        endMs: 7124,
        durationMs: 560,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Entschuldigen Sie.',
        turkishText: 'Affedersiniz.',
        englishExplanation: 'Calling attention politely ("Entschuldigen Sie").',
      },
      {
        id: 'de-l1-u05-s004',
        segmentIndex: 4,
        startMs: 7304,
        endMs: 8326,
        durationMs: 1022,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ja, bitte?',
        turkishText: 'Evet, buyrun?',
        englishExplanation: '"Ja, bitte?" = Yes, how can I help you?',
      },
      {
        id: 'de-l1-u05-s005',
        segmentIndex: 5,
        startMs: 8750,
        endMs: 10278,
        durationMs: 1528,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wo ist die Goethestraße bitte?',
        turkishText: 'Goethe Caddesi nerede lütfen?',
        englishExplanation: '"Wo ist...?" = Where is...? ("die Straße" is feminine).',
      },
      {
        id: 'de-l1-u05-s006',
        segmentIndex: 6,
        startMs: 10618,
        endMs: 12518,
        durationMs: 1900,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Die Goethestraße ist dort drüben.',
        turkishText: 'Goethe Caddesi orada.',
        englishExplanation: '"Dort drüben" = over there / across.',
      },
      {
        id: 'de-l1-u05-s007',
        segmentIndex: 7,
        startMs: 12826,
        endMs: 13706,
        durationMs: 880,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Und der Opernplatz?',
        turkishText: 'Ya Opera Meydanı?',
        englishExplanation: '"Der Platz" is masculine ("der Opernplatz").',
      },
      {
        id: 'de-l1-u05-s008',
        segmentIndex: 8,
        startMs: 13706,
        endMs: 15622,
        durationMs: 1916,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Der Opernplatz ist hier.',
        turkishText: 'Opera Meydanı burada.',
        englishExplanation: '"Hier" = here.',
      },
      {
        id: 'de-l1-u05-s009',
        segmentIndex: 9,
        startMs: 16378,
        endMs: 17338,
        durationMs: 960,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Und wie geht es Ihnen?',
        turkishText: 'Peki siz nasılsınız?',
        englishExplanation: 'Transition from direction asking to personal well-being greeting.',
      },
      {
        id: 'de-l1-u05-s010',
        segmentIndex: 10,
        startMs: 17678,
        endMs: 19098,
        durationMs: 1420,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Mir? Sehr gut, danke.',
        turkishText: 'Ben mi? Çok iyi, teşekkürler.',
        englishExplanation: '"Mir?" = Dative pronoun ("To me? / Who, me?").',
      },
      {
        id: 'de-l1-u05-s011',
        segmentIndex: 11,
        startMs: 19338,
        endMs: 20614,
        durationMs: 1276,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Auf Wiedersehen.',
        turkishText: 'Hoşça kalın.',
        englishExplanation: 'Formal farewell ("Auf Wiedersehen" = Until we see each other again).',
      },
      {
        id: 'de-l1-u05-s012',
        segmentIndex: 12,
        startMs: 20954,
        endMs: 21990,
        durationMs: 1036,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Auf Wiedersehen.',
        turkishText: 'Hoşça kalın.',
        englishExplanation: 'Reciprocated farewell.',
      },
    ],
    keyVocab: [
      { term: 'Wo ist...?', tr: '... nerede?', en: 'Where is...?' },
      { term: 'Die Straße', tr: 'Cadde / Sokak', en: 'The street' },
      { term: 'Der Platz', tr: 'Meydan', en: 'The square' },
      { term: 'Dort drüben', tr: 'Orada / Karşıda', en: 'Over there' },
      { term: 'Hier', tr: 'Burada', en: 'Here' },
      { term: 'Mir?', tr: 'Bana mı? / Ben mi?', en: 'Me? (dative response)' },
      { term: 'Auf Wiedersehen', tr: 'Hoşça kalın', en: 'Goodbye' },
    ],
  },
  {
    unitNumber: 6,
    title: 'Buluşma & Bir Şeyler Yeme/İçme Teklifi',
    contextTr: 'Brigitte ve Günther karşılaşır. Birlikte bir şeyler yiyip içme teklifi ve konum seçimi yapılır.',
    contextEn: 'Brigitte and Günther meet up and discuss eating/drinking at Opernplatz.',
    contextDe: 'Treffen von Brigitte und Günther und Verabredung zum Essen/Trinken.',
    startMs: 5686,
    endMs: 17926,
    durationMs: 12240,
    audioFileName: 'Pimsleur German 1 - Unit 06.mp3',
    lines: [
      {
        id: 'de-l1-u06-s003',
        segmentIndex: 3,
        startMs: 5686,
        endMs: 7270,
        durationMs: 1584,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Guten Tag, Brigitte.',
        turkishText: 'İyi günler, Brigitte.',
        englishExplanation: 'Friendly greeting using first name.',
      },
      {
        id: 'de-l1-u06-s004',
        segmentIndex: 4,
        startMs: 7546,
        endMs: 8426,
        durationMs: 880,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Guten Tag, Günther.',
        turkishText: 'İyi günler, Günther.',
        englishExplanation: 'Polite inquiry in response.',
      },
      {
        id: 'de-l1-u06-s005',
        segmentIndex: 5,
        startMs: 8506,
        endMs: 9866,
        durationMs: 1360,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Wie geht es Ihnen?',
        turkishText: 'Nasılsınız?',
        englishExplanation: 'Polite greeting query.',
      },
      {
        id: 'de-l1-u06-s006',
        segmentIndex: 6,
        startMs: 9866,
        endMs: 10246,
        durationMs: 380,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Gut, danke.',
        turkishText: 'İyi, teşekkürler.',
        englishExplanation: 'Short acknowledgement.',
      },
      {
        id: 'de-l1-u06-s007',
        segmentIndex: 7,
        startMs: 10466,
        endMs: 11766,
        durationMs: 1300,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ich möchte etwas essen.',
        turkishText: 'Bir şeyler yemek istiyorum.',
        englishExplanation: '"Ich möchte..." = I would like to... (modal verb with infinitive).',
      },
      {
        id: 'de-l1-u06-s008',
        segmentIndex: 8,
        startMs: 11806,
        endMs: 12646,
        durationMs: 840,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Sie auch?',
        turkishText: 'Siz de mi?',
        englishExplanation: '"Sie auch?" = You too?',
      },
      {
        id: 'de-l1-u06-s009',
        segmentIndex: 9,
        startMs: 13070,
        endMs: 15078,
        durationMs: 2008,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, ich möchte nur etwas trinken.',
        turkishText: 'Hayır, sadece bir şeyler içmek istiyorum.',
        englishExplanation: '"Nur" = only. Modal verb syntax ("möchte" + infinitive at end).',
      },
      {
        id: 'de-l1-u06-s010',
        segmentIndex: 10,
        startMs: 15470,
        endMs: 16654,
        durationMs: 1184,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wo? Am Opernplatz?',
        turkishText: 'Nerede? Opera Meydanı\'nda mı?',
        englishExplanation: '"Am" = an + dem (at the square: "Am Opernplatz").',
      },
      {
        id: 'de-l1-u06-s011',
        segmentIndex: 11,
        startMs: 16654,
        endMs: 17926,
        durationMs: 1272,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ja gut.',
        turkishText: 'Evet, güzel.',
        englishExplanation: 'Agreement to the location proposal.',
      },
    ],
    keyVocab: [
      { term: 'Ich möchte...', tr: '... istiyorum / arzu ederim', en: 'I would like to...' },
      { term: 'Essen', tr: 'Yemek yemek', en: 'To eat' },
      { term: 'Trinken', tr: 'İçmek', en: 'To drink' },
      { term: 'Etwas', tr: 'Bir şeyler / biraz', en: 'Something' },
      { term: 'Sie auch?', tr: 'Siz de mi?', en: 'You too?' },
      { term: 'Am Opernplatz', tr: 'Opera Meydanı\'nda', en: 'At Opernplatz' },
      { term: 'Ja, gut', tr: 'Evet, iyi / tamam', en: 'Yes, good / agreed' },
    ],
  },
  {
    unitNumber: 7,
    title: 'Zaman & Mekan ("Bei mir")',
    contextTr: 'Yemek ve içecek için zamanlama planlaması (wann, jetzt, später) ve eve davet ifadesi (bei mir).',
    contextEn: 'Discussing timing (now, later) and inviting to one\'s place ("bei mir").',
    contextDe: 'Zeitplanung und Einladung nach Hause ("bei mir").',
    startMs: 6330,
    endMs: 16646,
    durationMs: 10316,
    audioFileName: 'Pimsleur German 1 - Unit 07.mp3',
    lines: [
      {
        id: 'de-l1-u07-s003',
        segmentIndex: 3,
        startMs: 6330,
        endMs: 8326,
        durationMs: 1996,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Entschuldigen Sie, Brigitte. Ja?',
        turkishText: 'Affedersiniz Brigitte. Evet?',
        englishExplanation: 'Polite attention call.',
      },
      {
        id: 'de-l1-u07-s004',
        segmentIndex: 4,
        startMs: 8538,
        endMs: 9618,
        durationMs: 1080,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wann möchten Sie etwas essen?',
        turkishText: 'Ne zaman bir şeyler yemek istersiniz?',
        englishExplanation: '"Wann...?" = When...?',
      },
      {
        id: 'de-l1-u07-s005',
        segmentIndex: 5,
        startMs: 9698,
        endMs: 11866,
        durationMs: 2168,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Jetzt? Nein, nicht jetzt.',
        turkishText: 'Şimdi mi? Hayır, şimdi değil.',
        englishExplanation: '"Jetzt" = now; negation with "nicht".',
      },
      {
        id: 'de-l1-u07-s006',
        segmentIndex: 6,
        startMs: 11866,
        endMs: 14306,
        durationMs: 2440,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Später bitte, aber ich möchte jetzt etwas trinken.',
        turkishText: 'Daha sonra lütfen, ama şimdi bir şeyler içmek istiyorum.',
        englishExplanation: 'Contrasting timing preference with conjunction "aber".',
      },
      {
        id: 'de-l1-u07-s007',
        segmentIndex: 7,
        startMs: 14426,
        endMs: 15286,
        durationMs: 860,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Wo, bei mir?',
        turkishText: 'Nerede, bende mi?',
        englishExplanation: '"Bei mir" = at my place / at home with me.',
      },
      {
        id: 'de-l1-u07-s008',
        segmentIndex: 8,
        startMs: 15526,
        endMs: 16646,
        durationMs: 1120,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ja, gerne.',
        turkishText: 'Evet, memnuniyetle.',
        englishExplanation: '"Gerne" = gladly / with pleasure.',
      },
    ],
    keyVocab: [
      { term: 'Wann...?', tr: 'Ne zaman?', en: 'When...?' },
      { term: 'Jetzt', tr: 'Şimdi', en: 'Now' },
      { term: 'Nicht jetzt', tr: 'Şimdi değil', en: 'Not now' },
      { term: 'Später', tr: 'Daha sonra / Sonra', en: 'Later' },
      { term: 'Bei mir', tr: 'Bende / Benim evimde', en: 'At my place' },
      { term: 'Gerne', tr: 'Memnuniyetle / Seve seve', en: 'Gladly / With pleasure' },
    ],
  },
  {
    unitNumber: 8,
    title: 'Restoran Siparişi & "Wie bitte?"',
    contextTr: 'Restoranda Peter ve Ingrid içecek siparişi verir. Garsona seslenme ve duyamadığında kibarca tekrarlatma kalıbı (Wie bitte?).',
    contextEn: 'Ordering drinks in a restaurant and politely asking for repetition with "Wie bitte?".',
    contextDe: 'Getränke im Restaurant bestellen und "Wie bitte?" verwenden.',
    startMs: 18010,
    endMs: 40262,
    durationMs: 22252,
    audioFileName: 'Pimsleur German 1 - Unit 08.mp3',
    lines: [
      {
        id: 'de-l1-u08-s008',
        segmentIndex: 8,
        startMs: 18010,
        endMs: 19814,
        durationMs: 1804,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ingrid, möchten Sie jetzt essen?',
        turkishText: 'Ingrid, şimdi yemek yemek ister misiniz?',
        englishExplanation: 'Question asking about immediate dining interest.',
      },
      {
        id: 'de-l1-u08-s009',
        segmentIndex: 9,
        startMs: 20174,
        endMs: 20674,
        durationMs: 500,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Danke, Peter.',
        turkishText: 'Teşekkürler, Peter.',
        englishExplanation: 'Polite initial decline.',
      },
      {
        id: 'de-l1-u08-s010',
        segmentIndex: 10,
        startMs: 20794,
        endMs: 21474,
        durationMs: 680,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Jetzt nicht.',
        turkishText: 'Şimdi değil.',
        englishExplanation: 'Temporal negation ("Jetzt nicht" = Not now).',
      },
      {
        id: 'de-l1-u08-s011',
        segmentIndex: 11,
        startMs: 21614,
        endMs: 23494,
        durationMs: 1880,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Aber ich möchte etwas trinken.',
        turkishText: 'Ama bir şeyler içmek istiyorum.',
        englishExplanation: 'Desire for a beverage instead.',
      },
      {
        id: 'de-l1-u08-s012',
        segmentIndex: 12,
        startMs: 23770,
        endMs: 24230,
        durationMs: 460,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, gut.',
        turkishText: 'Evet, güzel.',
        englishExplanation: 'Agreement to have drinks.',
      },
      {
        id: 'de-l1-u08-s013',
        segmentIndex: 13,
        startMs: 24490,
        endMs: 26150,
        durationMs: 1660,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Was möchten Sie trinken?',
        turkishText: 'Ne içmek istersiniz?',
        englishExplanation: '"Was...?" = What...?',
      },
      {
        id: 'de-l1-u08-s014',
        segmentIndex: 14,
        startMs: 26862,
        endMs: 28422,
        durationMs: 1560,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ich möchte Wein trinken.',
        turkishText: 'Şarap içmek istiyorum.',
        englishExplanation: 'Desire for wine.',
      },
      {
        id: 'de-l1-u08-s015',
        segmentIndex: 15,
        startMs: 28602,
        endMs: 30406,
        durationMs: 1804,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, nein, ich trinke ein Bier.',
        turkishText: 'Hayır, hayır, bir bira içerim.',
        englishExplanation: 'Changing mind from "Wein" (wine) to "ein Bier" (a beer).',
      },
      {
        id: 'de-l1-u08-s016',
        segmentIndex: 16,
        startMs: 31032,
        endMs: 33286,
        durationMs: 2254,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ich auch, ich möchte auch ein Bier trinken.',
        turkishText: 'Ben de, ben de bir bira içmek istiyorum.',
        englishExplanation: '"Ich auch" = Me too; "auch" = also.',
      },
      {
        id: 'de-l1-u08-s017',
        segmentIndex: 17,
        startMs: 33720,
        endMs: 35718,
        durationMs: 1998,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Entschuldigen Sie, zwei Bier bitte.',
        turkishText: 'Affedersiniz, iki bira lütfen.',
        englishExplanation: 'Ordering pattern: Number + Noun + "bitte" ("zwei Bier bitte").',
      },
      {
        id: 'de-l1-u08-s018',
        segmentIndex: 18,
        startMs: 36270,
        endMs: 37766,
        durationMs: 1496,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wie bitte? Essen?',
        turkishText: 'Efendim? Yemek mi?',
        englishExplanation: '"Wie bitte?" = Pardon? / What did you say? (polite request for repetition).',
      },
      {
        id: 'de-l1-u08-s019',
        segmentIndex: 19,
        startMs: 38170,
        endMs: 39334,
        durationMs: 1164,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Nein, jetzt nicht.',
        turkishText: 'Hayır, şimdi değil.',
        englishExplanation: 'Declining food for now.',
      },
      {
        id: 'de-l1-u08-s020',
        segmentIndex: 20,
        startMs: 39642,
        endMs: 40262,
        durationMs: 620,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Später.',
        turkishText: 'Daha sonra.',
        englishExplanation: 'Specifying postponed time ("Später").',
      },
    ],
    keyVocab: [
      { term: 'Was möchten Sie trinken?', tr: 'Ne içmek istersiniz?', en: 'What would you like to drink?' },
      { term: 'Wein', tr: 'Şarap', en: 'Wine' },
      { term: 'Ein Bier / Zwei Bier', tr: 'Bir bira / İki bira', en: 'A beer / Two beers' },
      { term: 'Ich auch', tr: 'Ben de', en: 'Me too' },
      { term: 'Wie bitte?', tr: 'Efendim? / Nasıl anlayamadım?', en: 'Pardon? / Could you repeat?' },
    ],
  },
  {
    unitNumber: 9,
    title: '"Sagen Sie!" & Mekan Konumu',
    contextTr: 'Michael ve Ingrid buluşur. "Söyleyin bana / Baksanıza" anlamında Sagen Sie! kullanımı ve Beethoven Caddesi\'ndeki restorana gitme kararı.',
    contextEn: 'Michael and Ingrid meet, using "Sagen Sie!" and choosing a restaurant on Beethovenstraße.',
    contextDe: 'Verabredung von Michael und Ingrid im Restaurant in der Beethovenstraße.',
    startMs: 14714,
    endMs: 43942,
    durationMs: 29228,
    audioFileName: 'Pimsleur German 1 - Unit 09.mp3',
    lines: [
      {
        id: 'de-l1-u09-s004',
        segmentIndex: 4,
        startMs: 14714,
        endMs: 15654,
        durationMs: 940,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Sagen Sie!',
        turkishText: 'Söyler misiniz!',
        englishExplanation: '"Sagen Sie" = Tell me / Say (conversational opener).',
      },
      {
        id: 'de-l1-u09-s005',
        segmentIndex: 5,
        startMs: 17274,
        endMs: 17994,
        durationMs: 720,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Guten Tag, Ingrid.',
        turkishText: 'İyi günler, Ingrid.',
        englishExplanation: 'Daytime greeting.',
      },
      {
        id: 'de-l1-u09-s006',
        segmentIndex: 6,
        startMs: 18154,
        endMs: 19334,
        durationMs: 1180,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wie geht es Ihnen?',
        turkishText: 'Nasılsınız?',
        englishExplanation: 'Polite inquiry on well-being.',
      },
      {
        id: 'de-l1-u09-s007',
        segmentIndex: 7,
        startMs: 19546,
        endMs: 21478,
        durationMs: 1932,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Es geht mir gut, Michael. Danke.',
        turkishText: 'İyiyim, Michael. Teşekkürler.',
        englishExplanation: 'Full phrase: "Es geht mir gut" (It goes well with me).',
      },
      {
        id: 'de-l1-u09-s008',
        segmentIndex: 8,
        startMs: 21850,
        endMs: 24262,
        durationMs: 2412,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Sagen Sie, Ingrid, was möchten Sie jetzt machen?',
        turkishText: 'Söyler misiniz, Ingrid, şimdi ne yapmak istersiniz?',
        englishExplanation: '"Machen" = to do / to make.',
      },
      {
        id: 'de-l1-u09-s009',
        segmentIndex: 9,
        startMs: 24442,
        endMs: 26982,
        durationMs: 2540,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ich? Ich möchte etwas trinken. Und Sie?',
        turkishText: 'Ben mi? Ben bir şeyler içmek istiyorum. Ya siz?',
        englishExplanation: 'Personal emphasis ("Ich?").',
      },
      {
        id: 'de-l1-u09-s010',
        segmentIndex: 10,
        startMs: 27460,
        endMs: 28700,
        durationMs: 1240,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ich möchte jetzt etwas essen.',
        turkishText: 'Şimdi bir şeyler yemek istiyorum.',
        englishExplanation: 'Declaring personal dining interest.',
      },
      {
        id: 'de-l1-u09-s011',
        segmentIndex: 11,
        startMs: 29040,
        endMs: 30566,
        durationMs: 1526,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Möchten Sie mit mir essen?',
        turkishText: 'Benimle yemek yemek ister misiniz?',
        englishExplanation: '"Mit mir" = with me.',
      },
      {
        id: 'de-l1-u09-s012',
        segmentIndex: 12,
        startMs: 30778,
        endMs: 31438,
        durationMs: 660,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ja, aber wo?',
        turkishText: 'Evet, ama nerede?',
        englishExplanation: 'Inquiring venue.',
      },
      {
        id: 'de-l1-u09-s013',
        segmentIndex: 13,
        startMs: 31618,
        endMs: 33606,
        durationMs: 1988,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Im Restaurant zum Bären?',
        turkishText: 'Restaurant zum Bären\'de mi?',
        englishExplanation: '"Im" = in dem (in/at the restaurant: "Im Restaurant zum Bären").',
      },
      {
        id: 'de-l1-u09-s014',
        segmentIndex: 14,
        startMs: 33914,
        endMs: 35254,
        durationMs: 1340,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Wo ist das Restaurant zum Bären?',
        turkishText: 'Restaurant zum Bären nerede?',
        englishExplanation: 'Asking for specific venue location.',
      },
      {
        id: 'de-l1-u09-s015',
        segmentIndex: 15,
        startMs: 35534,
        endMs: 37254,
        durationMs: 1720,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'In der Beethovenstraße.',
        turkishText: 'Beethoven Caddesi\'nde.',
        englishExplanation: 'Dative feminine location: "In der [Straße]".',
      },
      {
        id: 'de-l1-u09-s016',
        segmentIndex: 16,
        startMs: 37562,
        endMs: 39366,
        durationMs: 1804,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ah ja, ich weiß, wo das ist.',
        turkishText: 'Ah evet, nerede olduğunu biliyorum.',
        englishExplanation: '"Ich weiß..." = I know... (subordinate clause).',
      },
      {
        id: 'de-l1-u09-s017',
        segmentIndex: 17,
        startMs: 39962,
        endMs: 42250,
        durationMs: 2288,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Und ich möchte auch ein bisschen Wein trinken.',
        turkishText: 'Ve ben de biraz şarap içmek istiyorum.',
        englishExplanation: 'Adding preference: "ein bisschen Wein".',
      },
      {
        id: 'de-l1-u09-s018',
        segmentIndex: 18,
        startMs: 42250,
        endMs: 43942,
        durationMs: 1692,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ja, gut, ich auch.',
        turkishText: 'Evet, güzel, ben de.',
        englishExplanation: 'Consensus ("ich auch").',
      },
    ],
    keyVocab: [
      { term: 'Sagen Sie...', tr: 'Söyler misiniz... / Baksanıza...', en: 'Tell me... / Say...' },
      { term: 'Es geht mir gut', tr: 'İyiyim', en: 'I am doing well' },
      { term: 'Was möchten Sie machen?', tr: 'Ne yapmak istersiniz?', en: 'What would you like to do?' },
      { term: 'Mit mir', tr: 'Benimle', en: 'With me' },
      { term: 'Im Restaurant', tr: 'Restoranda', en: 'In/at the restaurant' },
      { term: 'In der Beethovenstraße', tr: 'Beethoven Caddesi\'nde', en: 'On Beethoven Street' },
      { term: 'Ich weiß, wo das ist', tr: 'Nerede olduğunu biliyorum', en: 'I know where that is' },
    ],
  },
  {
    unitNumber: 10,
    title: 'Randevu Saati Belirleme ("Um wie viel Uhr?")',
    contextTr: 'Birlikte yemek yeme planı (zusammen essen) ve saati netleştirme (um wie viel Uhr?, viel später, um 9 Uhr).',
    contextEn: 'Arranging a dinner time together with specific time expressions.',
    contextDe: 'Uhrzeit für gemeinsames Essen vereinbaren ("um wie viel Uhr?", "um 9 Uhr").',
    startMs: 11450,
    endMs: 27590,
    durationMs: 16140,
    audioFileName: 'Pimsleur German 1 - Unit 10.mp3',
    lines: [
      {
        id: 'de-l1-u10-s005',
        segmentIndex: 5,
        startMs: 11450,
        endMs: 13862,
        durationMs: 2412,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Peter, ich möchte mit Ihnen zusammen essen.',
        turkishText: 'Peter, sizinle birlikte yemek yemek istiyorum.',
        englishExplanation: '"Mit Ihnen" = with you (formal); "zusammen" = together.',
      },
      {
        id: 'de-l1-u10-s006',
        segmentIndex: 6,
        startMs: 14222,
        endMs: 16014,
        durationMs: 1792,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Gerne, aber um wie viel Uhr?',
        turkishText: 'Memnuniyetle, ama saat kaçta?',
        englishExplanation: '"Um wie viel Uhr?" = At what time / What time?',
      },
      {
        id: 'de-l1-u10-s007',
        segmentIndex: 7,
        startMs: 16014,
        endMs: 16958,
        durationMs: 944,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Zwei.',
        turkishText: 'İki.',
        englishExplanation: 'Suggesting 2 o\'clock.',
      },
      {
        id: 'de-l1-u10-s008',
        segmentIndex: 8,
        startMs: 16958,
        endMs: 17658,
        durationMs: 700,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Nein, nein, später.',
        turkishText: 'Hayır, hayır, daha sonra.',
        englishExplanation: 'Rejecting suggested early time.',
      },
      {
        id: 'de-l1-u10-s009',
        segmentIndex: 9,
        startMs: 18018,
        endMs: 19270,
        durationMs: 1252,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Viel später.',
        turkishText: 'Çok daha sonra.',
        englishExplanation: '"Viel" = much / a lot ("viel später" = much later).',
      },
      {
        id: 'de-l1-u10-s010',
        segmentIndex: 10,
        startMs: 19450,
        endMs: 20518,
        durationMs: 1068,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Ah, ich verstehe.',
        turkishText: 'Ah, anlıyorum.',
        englishExplanation: 'Comprehension confirmation ("ich verstehe").',
      },
      {
        id: 'de-l1-u10-s011',
        segmentIndex: 11,
        startMs: 20922,
        endMs: 23114,
        durationMs: 2192,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Um 8 Uhr oder um 9 Uhr.',
        turkishText: 'Saat 8\'de veya saat 9\'da.',
        englishExplanation: '"Oder" = or ("Um 8 Uhr oder um 9 Uhr?").',
      },
      {
        id: 'de-l1-u10-s012',
        segmentIndex: 12,
        startMs: 23114,
        endMs: 24486,
        durationMs: 1372,
        speaker: 'GERMAN_FEMALE',
        speakerDisplayName: 'Almanca Kadın Konuşmacı',
        germanText: 'Ja, um 9 Uhr.',
        turkishText: 'Evet, saat 9\'da.',
        englishExplanation: '"Um [X] Uhr" = At [X] o\'clock.',
      },
      {
        id: 'de-l1-u10-s013',
        segmentIndex: 13,
        startMs: 25262,
        endMs: 26302,
        durationMs: 1040,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Also, dann bis 9 Uhr.',
        turkishText: 'O halde saat 9\'da görüşmek üzere.',
        englishExplanation: '"Also, dann bis..." = Well then, see you at / until...',
      },
      {
        id: 'de-l1-u10-s014',
        segmentIndex: 14,
        startMs: 26482,
        endMs: 27590,
        durationMs: 1108,
        speaker: 'GERMAN_MALE',
        speakerDisplayName: 'Almanca Erkek Konuşmacı',
        germanText: 'Auf Wiedersehen!',
        turkishText: 'Hoşça kalın!',
        englishExplanation: 'Reciprocal farewell.',
      },
    ],
    keyVocab: [
      { term: 'Mit Ihnen zusammen', tr: 'Sizinle birlikte', en: 'Together with you' },
      { term: 'Um wie viel Uhr?', tr: 'Saat kaçta?', en: 'At what time?' },
      { term: 'Viel später', tr: 'Çok daha sonra', en: 'Much later' },
      { term: 'Um 8 Uhr / Um 9 Uhr', tr: 'Saat 8\'de / Saat 9\'da', en: 'At 8 o\'clock / At 9 o\'clock' },
      { term: 'Oder', tr: 'Veya / Yoksa', en: 'Or' },
      { term: 'Also, dann bis...', tr: 'O halde ...\'e kadar / ...\'de görüşmek üzere', en: 'Well then, until...' },
    ],
  },
];
